server:
  port: 8082
spring:
  application:
    name: notification
  datasource:
    url: jdbc:h2:file:F:\MicroServicesCourse\Ecommerce\OrderService\src\main\resources\data\Ecommerce;AUTO_SERVER=true
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key

management:
  tracing:
    sampling:
      probability: 1.0  # Sample 100% of requests for testing; adjust as needed.
micrometer:
  tracing:
    reporter:
      zipkin:
        enabled: true
        base-url: http://localhost:9411/api/v2/spans